In [2]:
import numpy as np
# %matplotlib inline 使matplotlib图表在notebook中直接显示
%matplotlib inline

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array((5, 6, 7))
c = np.array([[1, 2, 3], [1, 2, 4], [4, 6, 7]])
print(a)
print(b)
print(c)

[1 2 3 4]
[5 6 7]
[[1 2 3]
 [1 2 4]
 [4 6 7]]


In [4]:
print(a.shape)

(4,)


In [5]:
print(b.shape)

(3,)


In [6]:
print(c.shape)

(3, 3)


In [7]:
c.reshape(9, 1)

array([[1],
       [2],
       [3],
       [1],
       [2],
       [4],
       [4],
       [6],
       [7]])

In [8]:
c.reshape(1, 9)

array([[1, 2, 3, 1, 2, 4, 4, 6, 7]])

reshape并不会单独创建一个数组，而是在原有数组的基础上共享存储空间，修改reshape数组的值，会使得原有的数组数值也发生改变

In [9]:
# 数组的数据类型
print(c.dtype)

int32


In [10]:
c.astype(np.float)

array([[1., 2., 3.],
       [1., 2., 4.],
       [4., 6., 7.]])

In [11]:
# 不包括终止值1,第三个参数表示步长
a = np.arange(0, 1, .1)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [12]:
# 使用linspace（）通过指定开始值、终止值和元素个数来生成一个等差数列的一维数组，
# 可以通过endpoint参数来指定是否包含终值，默认值为TRUE
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.linspace(0, 1, 10, endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [14]:
# 使用logspace()通过指定开始值、终止值和元素个数来生成一个以10为底数列的一维数组,通过base参数可以改变底数
np.logspace(0, 2, 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [15]:
np.logspace(0, 2, 5, base=2, endpoint=False)

array([1.        , 1.31950791, 1.74110113, 2.29739671, 3.03143313])

In [16]:
# ones(),zeros(),empty()函数可以创建一个元素为1,0，空的数组，第一个参数可以指定数组的形状，
# 第二个参数可以指定数组元素的类型
np.ones(4, np.int)

array([1, 1, 1, 1])

In [17]:
np.ones((4, 4), np.int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
# 使用函数来基于下标创建数组
# #此处应该注意，如果函数只有一个输入，那么数组就只能是一维的
def func(i):
    return i % 4 + 1

np.fromfunction(func, (10,))

array([1., 2., 3., 4., 1., 2., 3., 4., 1., 2.])

In [19]:
# 这种方法创建的数组，函数有多少个参数，就只能产生多少维的数组
def func2(i, j):
    return (i + 1) * (j + 1)
# #下标是从0开始计数的
np.fromfunction(func2, (9, 9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [27]:
# 自定义数组类型
persontype = np.dtype({
    'names': ['name', 'weight', 'age'],    # 定义列
    'formats': ['S30', 'f', 'i']}, align=True)  # 定义列类型

a = np.array([('zhang', 80.0, 18), ('wang', 70.5, 25)], dtype=persontype)
print(a)
print(a[0][1])
print(a[0]['weight'])

[(b'zhang', 80. , 18) (b'wang', 70.5, 25)]
80.0
80.0


In [29]:
# 创建共享内存数组
a = np.array([[0, 1], [2, 3], [4, 5]], dtype=np.float32)
b = a.view(np.uint32)
c = a.view(np.uint8)
print(a)
print(b)
print(c)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
[[         0 1065353216]
 [1073741824 1077936128]
 [1082130432 1084227584]]
[[  0   0   0   0   0   0 128  63]
 [  0   0   0  64   0   0  64  64]
 [  0   0 128  64   0   0 160  64]]


In [30]:
c[0, 4] = 32
print(a)
print(c)

[[0.        1.0000038]
 [2.        3.       ]
 [4.        5.       ]]
[[  0   0   0   0  32   0 128  63]
 [  0   0   0  64   0   0  64  64]
 [  0   0 128  64   0   0 160  64]]


In [31]:
a = np.arange(0, 5)
b = np.arange(4, 9)
np.add(a, b)

array([ 4,  6,  8, 10, 12])